    <div id="menu-popup" class="menu-popup" role="dialog" aria-modal="true" aria-labelledby="menu-popup-title" aria-hidden="true">
        <div class="menu-popup-backdrop" data-menu-popup-close></div>
        <div class="menu-popup-panel">
            <button type="button" class="menu-popup-close" aria-label="Close menu" data-menu-popup-close>&times;</button>
            <section id="menu" class="menu-template">
        <div class="container">
            <div class="section-title fade-in">
                <h2 id="menu-popup-title">Our Menu</h2>
                <p>Explore our delicious offerings.</p>
            </div>

            <div class="menu-categories fade-in">
                <!-- CHICKEN WINGS -->
                <div class="menu-category">
                    <button class="category-card" type="button" aria-haspopup="dialog"
                        data-category-image="images/unlimited-rice-wings-sharp.png">
                        <img src="images/unlimited-rice-wings-sharp.png" alt="Chicken wings" loading="lazy" decoding="async">
                        <span class="category-card-title">CHICKEN WINGS</span>
                    </button>
                    <div class="category-content">
                        <div class="menu-grid">
                            <div class="menu-item" data-item-name="Wings Solo" data-item-sub="(8 slices)" data-item-price="&#8369;230" data-category="CHICKEN WINGS"><div class="menu-item-info"><h4>Wings Solo</h4><p>(8 slices)</p></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;230</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Wings Tropa" data-item-sub="(12 slices)" data-item-price="&#8369;285" data-category="CHICKEN WINGS"><div class="menu-item-info"><h4>Wings Tropa</h4><p>(12 slices)</p></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;285</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Bilao Wings A" data-item-sub="(30 slices)" data-item-price="&#8369;699" data-category="CHICKEN WINGS"><div class="menu-item-info"><h4>Bilao Wings A</h4><p>(30 slices)</p></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;699</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Bilao Wings B" data-item-sub="(40 slices)" data-item-price="&#8369;850" data-category="CHICKEN WINGS"><div class="menu-item-info"><h4>Bilao Wings B</h4><p>(40 slices)</p></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;850</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Bilao Wings C" data-item-sub="(50 slices)" data-item-price="&#8369;999" data-category="CHICKEN WINGS"><div class="menu-item-info"><h4>Bilao Wings C</h4><p>(50 slices)</p></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;999</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Bilao Wings & Shanghai" data-item-sub="" data-item-price="&#8369;550" data-category="CHICKEN WINGS"><div class="menu-item-info"><h4>Bilao Wings & Shanghai</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;550</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                        </div>
                    </div>
                </div>

                <!-- COMBO SNACKS -->
                <div class="menu-category">
                    <button class="category-card" type="button" aria-haspopup="dialog"
                        data-category-image="images/combo-snacks-hd.jpg">
                        <img src="images/combo-snacks-hd.jpg" alt="Combo snacks" loading="lazy" decoding="async">
                        <span class="category-card-title">COMBO SNACKS</span>
                    </button>
                    <div class="category-content">
                        <div class="menu-grid">
                            <div class="menu-item" data-item-name="Flavored Wings & Fries" data-item-sub="" data-item-price="&#8369;135" data-category="COMBO SNACKS"><div class="menu-item-info"><h4>Flavored Wings & Fries</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;135</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Flavored Wings & Nachos" data-item-sub="" data-item-price="&#8369;135" data-category="COMBO SNACKS"><div class="menu-item-info"><h4>Flavored Wings & Nachos</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;135</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Nachos & Quesadilla" data-item-sub="" data-item-price="&#8369;199" data-category="COMBO SNACKS"><div class="menu-item-info"><h4>Nachos & Quesadilla</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;199</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Fries & Nachos" data-item-sub="" data-item-price="&#8369;135" data-category="COMBO SNACKS"><div class="menu-item-info"><h4>Fries & Nachos</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;135</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Popshot & Fries" data-item-sub="" data-item-price="&#8369;135" data-category="COMBO SNACKS"><div class="menu-item-info"><h4>Popshot & Fries</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;135</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                        </div>
                    </div>
                </div>

                <!-- SOLO SNACKS -->
                <div class="menu-category">
                    <button class="category-card" type="button" aria-haspopup="dialog"
                        data-category-image="images/solo-snacks.jpg">
                        <img src="images/solo-snacks.jpg" alt="Solo snacks" loading="lazy" decoding="async">
                        <span class="category-card-title">SOLO SNACKS</span>
                    </button>
                    <div class="category-content">
                        <div class="menu-grid">
                            <div class="menu-item" data-item-name="Italian Spaghetti" data-item-sub="" data-item-price="&#8369;75" data-category="SOLO SNACKS"><div class="menu-item-info"><h4>Italian Spaghetti</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;75</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Korean Corndog" data-item-sub="" data-item-price="&#8369;89" data-category="SOLO SNACKS"><div class="menu-item-info"><h4>Korean Corndog</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;89</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Korean Corndog Trio" data-item-sub="" data-item-price="&#8369;260" data-category="SOLO SNACKS"><div class="menu-item-info"><h4>Korean Corndog Trio</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;260</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Cheesy Beef Quesadilla" data-item-sub="" data-item-price="&#8369;230" data-category="SOLO SNACKS"><div class="menu-item-info"><h4>Cheesy Beef Quesadilla</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;230</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Classic French Fries" data-item-sub="" data-item-price="&#8369;75" data-category="SOLO SNACKS"><div class="menu-item-info"><h4>Classic French Fries</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;75</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Flavored French Fries" data-item-sub="" data-item-price="&#8369;95" data-category="SOLO SNACKS"><div class="menu-item-info"><h4>Flavored French Fries</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;95</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Kropek Crackers" data-item-sub="" data-item-price="&#8369;75" data-category="SOLO SNACKS"><div class="menu-item-info"><h4>Kropek Crackers</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;75</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Cheesy Nachos Solo" data-item-sub="" data-item-price="&#8369;125" data-category="SOLO SNACKS"><div class="menu-item-info"><h4>Cheesy Nachos Solo</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;125</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Cheesy Nachos Tropa" data-item-sub="" data-item-price="&#8369;210" data-category="SOLO SNACKS"><div class="menu-item-info"><h4>Cheesy Nachos Tropa</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;210</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                        </div>
                    </div>
                </div>

                <!-- SHORT ORDERS -->
                <div class="menu-category">
                    <button class="category-card" type="button" aria-haspopup="dialog"
                        data-category-image="images/asset-contact-sheet.jpg">
                        <img src="images/asset-contact-sheet.jpg" alt="Short orders" loading="lazy" decoding="async">
                        <span class="category-card-title">SHORT ORDERS</span>
                    </button>
                    <div class="category-content">
                        <div class="menu-grid">
                            <div class="menu-item" data-item-name="Pancit Guisado" data-item-sub="" data-item-price="&#8369;220" data-category="SHORT ORDERS"><div class="menu-item-info"><h4>Pancit Guisado</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;220</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Breaded Fish Fillet" data-item-sub="" data-item-price="&#8369;220" data-category="SHORT ORDERS"><div class="menu-item-info"><h4>Breaded Fish Fillet</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;220</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Chicken Fingers" data-item-sub="" data-item-price="&#8369;245" data-category="SHORT ORDERS"><div class="menu-item-info"><h4>Chicken Fingers</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;245</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Lumpiang Shanghai" data-item-sub="" data-item-price="&#8369;245" data-category="SHORT ORDERS"><div class="menu-item-info"><h4>Lumpiang Shanghai</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;245</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Pork Sinigang" data-item-sub="" data-item-price="&#8369;245" data-category="SHORT ORDERS"><div class="menu-item-info"><h4>Pork Sinigang</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;245</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Bangus Sinigang" data-item-sub="" data-item-price="&#8369;240" data-category="SHORT ORDERS"><div class="menu-item-info"><h4>Bangus Sinigang</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;240</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Tuna Kinilaw" data-item-sub="" data-item-price="&#8369;240" data-category="SHORT ORDERS"><div class="menu-item-info"><h4>Tuna Kinilaw</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;240</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Calamares" data-item-sub="" data-item-price="&#8369;250" data-category="SHORT ORDERS"><div class="menu-item-info"><h4>Calamares</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;250</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Sinuglaw" data-item-sub="" data-item-price="&#8369;290" data-category="SHORT ORDERS"><div class="menu-item-info"><h4>Sinuglaw</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;290</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                        </div>
                    </div>
                </div>

                <!-- APPETIZERS -->
                <div class="menu-category">
                    <button class="category-card" type="button" aria-haspopup="dialog"
                        data-category-image="images/combo-snacks.jpg">
                        <img src="images/combo-snacks.jpg" alt="Appetizers" loading="lazy" decoding="async">
                        <span class="category-card-title">APPETIZERS</span>
                    </button>
                    <div class="category-content">
                        <div class="menu-grid">
                            <div class="menu-item" data-item-name="Fried Tofu" data-item-sub="" data-item-price="&#8369;45" data-category="APPETIZERS"><div class="menu-item-info"><h4>Fried Tofu</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;45</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="4pcs Lumpiang Ubod" data-item-sub="" data-item-price="&#8369;45" data-category="APPETIZERS"><div class="menu-item-info"><h4>4pcs Lumpiang Ubod</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;45</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="4pcs Pork Shrimp Siomai" data-item-sub="" data-item-price="&#8369;49" data-category="APPETIZERS"><div class="menu-item-info"><h4>4pcs Pork Shrimp Siomai</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;49</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="4pcs Shark's Fin Dumpling" data-item-sub="" data-item-price="&#8369;49" data-category="APPETIZERS"><div class="menu-item-info"><h4>4pcs Shark's Fin Dumpling</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;49</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="4pcs Japanese Siomai" data-item-sub="" data-item-price="&#8369;54" data-category="APPETIZERS"><div class="menu-item-info"><h4>4pcs Japanese Siomai</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;54</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="4pcs Lumpiang Shanghai" data-item-sub="" data-item-price="&#8369;59" data-category="APPETIZERS"><div class="menu-item-info"><h4>4pcs Lumpiang Shanghai</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;59</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                        </div>
                    </div>
                </div>

                <!-- BEVERAGES -->
                <div class="menu-category">
                    <button class="category-card" type="button" aria-haspopup="dialog"
                        data-category-image="images/beverages.jpg">
                        <img src="images/beverages.jpg" alt="Beverages" loading="lazy" decoding="async">
                        <span class="category-card-title">BEVERAGES</span>
                    </button>
                    <div class="category-content">
                        <div class="menu-grid">
                            <div class="menu-item" data-item-name="Iced Tea Blend" data-item-sub="" data-item-price="&#8369;75" data-category="BEVERAGES"><div class="menu-item-info"><h4>Iced Tea Blend</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;75</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Iced Tea Pitcher" data-item-sub="" data-item-price="&#8369;205" data-category="BEVERAGES"><div class="menu-item-info"><h4>Iced Tea Pitcher</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;205</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Bottled Softdrinks" data-item-sub="" data-item-price="&#8369;45" data-category="BEVERAGES"><div class="menu-item-info"><h4>Bottled Softdrinks</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;45</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Softdrinks in can" data-item-sub="" data-item-price="&#8369;80" data-category="BEVERAGES"><div class="menu-item-info"><h4>Softdrinks in can</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;80</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Purified Water" data-item-sub="" data-item-price="&#8369;30" data-category="BEVERAGES"><div class="menu-item-info"><h4>Purified Water</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;30</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Blue Lemonade" data-item-sub="" data-item-price="&#8369;75" data-category="BEVERAGES"><div class="menu-item-info"><h4>Blue Lemonade</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;75</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Pink Lemonade" data-item-sub="" data-item-price="&#8369;75" data-category="BEVERAGES"><div class="menu-item-info"><h4>Pink Lemonade</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;75</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Cucumber Lemonade" data-item-sub="" data-item-price="&#8369;75" data-category="BEVERAGES"><div class="menu-item-info"><h4>Cucumber Lemonade</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;75</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Lemonade Pitcher" data-item-sub="" data-item-price="&#8369;215" data-category="BEVERAGES"><div class="menu-item-info"><h4>Lemonade Pitcher</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;215</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                        </div>
                    </div>
                </div>

                <!-- SINGLE RICE MEALS -->
                <div class="menu-category">
                    <button class="category-card" type="button" aria-haspopup="dialog"
                        data-category-image="images/sizzling-rice-meal.jpg">
                        <img src="images/sizzling-rice-meal.jpg" alt="Single rice meals" loading="lazy" decoding="async">
                        <span class="category-card-title">SINGLE RICE MEALS</span>
                    </button>
                    <div class="category-content">
                        <div class="menu-grid">
                            <div class="menu-item" data-item-name="Flavored Wings Rice Meal" data-item-sub="(3 slices)" data-item-price="&#8369;135" data-category="SINGLE RICE MEALS"><div class="menu-item-info"><h4>Flavored Wings Rice Meal</h4><p>(3 slices)</p></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;135</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="ShanghaiSilog" data-item-sub="" data-item-price="&#8369;145" data-category="SINGLE RICE MEALS"><div class="menu-item-info"><h4>ShanghaiSilog</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;145</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Fish Fillet Rice Meal" data-item-sub="" data-item-price="&#8369;145" data-category="SINGLE RICE MEALS"><div class="menu-item-info"><h4>Fish Fillet Rice Meal</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;145</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Calamares Rice Meal" data-item-sub="" data-item-price="&#8369;145" data-category="SINGLE RICE MEALS"><div class="menu-item-info"><h4>Calamares Rice Meal</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;145</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="BurgerSteak Rice Meal" data-item-sub="" data-item-price="&#8369;145" data-category="SINGLE RICE MEALS"><div class="menu-item-info"><h4>BurgerSteak Rice Meal</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;145</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Porkchop Rice Meal" data-item-sub="" data-item-price="&#8369;145" data-category="SINGLE RICE MEALS"><div class="menu-item-info"><h4>Porkchop Rice Meal</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;145</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Shawarma Rice Meal" data-item-sub="" data-item-price="&#8369;145" data-category="SINGLE RICE MEALS"><div class="menu-item-info"><h4>Shawarma Rice Meal</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;145</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Beef Tapsilog" data-item-sub="" data-item-price="&#8369;165" data-category="SINGLE RICE MEALS"><div class="menu-item-info"><h4>Beef Tapsilog</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;165</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Chicken Fingers Rice Meal" data-item-sub="" data-item-price="&#8369;165" data-category="SINGLE RICE MEALS"><div class="menu-item-info"><h4>Chicken Fingers Rice Meal</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;165</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Pork Adobo Rice Meal" data-item-sub="" data-item-price="&#8369;165" data-category="SINGLE RICE MEALS"><div class="menu-item-info"><h4>Pork Adobo Rice Meal</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;165</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Pork Sisig Rice Meal" data-item-sub="" data-item-price="&#8369;165" data-category="SINGLE RICE MEALS"><div class="menu-item-info"><h4>Pork Sisig Rice Meal</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;165</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Lechon Kawali Rice Meal" data-item-sub="" data-item-price="&#8369;165" data-category="SINGLE RICE MEALS"><div class="menu-item-info"><h4>Lechon Kawali Rice Meal</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;165</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Grilled Liempo Rice Meal" data-item-sub="" data-item-price="&#8369;175" data-category="SINGLE RICE MEALS"><div class="menu-item-info"><h4>Grilled Liempo Rice Meal</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;175</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                        </div>
                    </div>
                </div>

                <!-- SIZZLING -->
                <div class="menu-category">
                    <button class="category-card" type="button" aria-haspopup="dialog"
                        data-category-image="images/sizzling.jpg">
                        <img src="images/sizzling.jpg" alt="Sizzling sisig" loading="lazy" decoding="async">
                        <span class="category-card-title">SIZZLING</span>
                    </button>
                    <div class="category-content">
                        <div class="menu-grid">
                            <div class="menu-item" data-item-name="Sizzling Sisig Tropa" data-item-sub="" data-item-price="&#8369;280" data-category="SIZZLING"><div class="menu-item-info"><h4>Sizzling Sisig Tropa</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;280</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Sizzling Lechon Kawali Tropa" data-item-sub="" data-item-price="&#8369;285" data-category="SIZZLING"><div class="menu-item-info"><h4>Sizzling Lechon Kawali Tropa</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;285</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Sizzling Buttered Shrimp" data-item-sub="" data-item-price="&#8369;290" data-category="SIZZLING"><div class="menu-item-info"><h4>Sizzling Buttered Shrimp</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;290</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                        </div>
                    </div>
                </div>

                <!-- SIZZLING RICE MEAL -->
                <div class="menu-category">
                    <button class="category-card" type="button" aria-haspopup="dialog"
                        data-category-image="images/sizzling-rice-meal.jpg">
                        <img src="images/sizzling-rice-meal.jpg" alt="Sizzling rice meal" loading="lazy" decoding="async">
                        <span class="category-card-title">SIZZLING RICE MEAL</span>
                    </button>
                    <div class="category-content">
                        <div class="menu-grid">
                            <div class="menu-item" data-item-name="Sizzling SisigSilog" data-item-sub="" data-item-price="&#8369;165" data-category="SIZZLING RICE MEAL"><div class="menu-item-info"><h4>Sizzling SisigSilog</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;165</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Sizzling LechonSilog" data-item-sub="" data-item-price="&#8369;165" data-category="SIZZLING RICE MEAL"><div class="menu-item-info"><h4>Sizzling LechonSilog</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;165</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Sizzling BurgerSteak" data-item-sub="" data-item-price="&#8369;165" data-category="SIZZLING RICE MEAL"><div class="menu-item-info"><h4>Sizzling BurgerSteak</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;165</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Sizzling LiemSilog" data-item-sub="" data-item-price="&#8369;175" data-category="SIZZLING RICE MEAL"><div class="menu-item-info"><h4>Sizzling LiemSilog</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;175</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                        </div>
                    </div>
                </div>

                <!-- TROPA SHARING PLATTER -->
                <div class="menu-category">
                    <button class="category-card" type="button" aria-haspopup="dialog"
                        data-category-image="images/tropa-sharing-platter.jpg">
                        <img src="images/tropa-sharing-platter.jpg" alt="Tropa sharing platter" loading="lazy" decoding="async">
                        <span class="category-card-title">TROPA SHARING PLATTER</span>
                    </button>
                    <div class="category-content">
                        <div class="menu-grid">
                            <div class="menu-item" data-item-name="Wings Platter" data-item-sub="" data-item-price="&#8369;365" data-category="TROPA SHARING PLATTER"><div class="menu-item-info"><h4>Wings Platter</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;365</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Wings & Fries Platter" data-item-sub="" data-item-price="&#8369;355" data-category="TROPA SHARING PLATTER"><div class="menu-item-info"><h4>Wings & Fries Platter</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;355</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Wings & Nachos Platter" data-item-sub="" data-item-price="&#8369;355" data-category="TROPA SHARING PLATTER"><div class="menu-item-info"><h4>Wings & Nachos Platter</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;355</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Lechon Kawali Tropa" data-item-sub="" data-item-price="&#8369;275" data-category="TROPA SHARING PLATTER"><div class="menu-item-info"><h4>Lechon Kawali Tropa</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;275</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Pork Sisig Tropa" data-item-sub="" data-item-price="&#8369;270" data-category="TROPA SHARING PLATTER"><div class="menu-item-info"><h4>Pork Sisig Tropa</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;270</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Lumpiang Shanghai Tropa" data-item-sub="" data-item-price="&#8369;250" data-category="TROPA SHARING PLATTER"><div class="menu-item-info"><h4>Lumpiang Shanghai Tropa</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;250</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                        </div>
                    </div>
                </div>

                <!-- EXTRA ADD-ONS -->
                <div class="menu-category">
                    <button class="category-card" type="button" aria-haspopup="dialog"
                        data-category-image="images/unlimited-rice-wings-variety.png">
                        <img src="images/unlimited-rice-wings-variety.png" alt="Extra add-ons" loading="lazy" decoding="async">
                        <span class="category-card-title">EXTRA ADD-ONS</span>
                    </button>
                    <div class="category-content">
                        <div class="menu-grid">
                            <div class="menu-item" data-item-name="Plain Rice" data-item-sub="" data-item-price="&#8369;30" data-category="EXTRA ADD-ONS"><div class="menu-item-info"><h4>Plain Rice</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;30</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Garlic Rice" data-item-sub="" data-item-price="&#8369;50" data-category="EXTRA ADD-ONS"><div class="menu-item-info"><h4>Garlic Rice</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;50</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Plain Rice Platter" data-item-sub="" data-item-price="&#8369;95" data-category="EXTRA ADD-ONS"><div class="menu-item-info"><h4>Plain Rice Platter</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;95</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Garlic Rice Platter" data-item-sub="" data-item-price="&#8369;135" data-category="EXTRA ADD-ONS"><div class="menu-item-info"><h4>Garlic Rice Platter</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;135</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Gravy" data-item-sub="" data-item-price="&#8369;30" data-category="EXTRA ADD-ONS"><div class="menu-item-info"><h4>Gravy</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;30</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                        </div>
                    </div>
                </div>

                <!-- DESSERT -->
                <div class="menu-category">
                    <button class="category-card" type="button" aria-haspopup="dialog"
                        data-category-image="images/dessert.jpg">
                        <img src="images/dessert.jpg" alt="Desserts" loading="lazy" decoding="async">
                        <span class="category-card-title">DESSERT</span>
                    </button>
                    <div class="category-content">
                        <div class="menu-grid">
                            <div class="menu-item" data-item-name="Fruit Salad Solo" data-item-sub="" data-item-price="&#8369;95" data-category="DESSERT"><div class="menu-item-info"><h4>Fruit Salad Solo</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;95</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Mango Bango Salad" data-item-sub="" data-item-price="&#8369;95" data-category="DESSERT"><div class="menu-item-info"><h4>Mango Bango Salad</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;95</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                            <div class="menu-item" data-item-name="Mango/Avocado Float" data-item-sub="" data-item-price="&#8369;180" data-category="DESSERT"><div class="menu-item-info"><h4>Mango/Avocado Float</h4></div><div class="menu-item-footer"><span class="menu-item-price">&#8369;180</span><span class="menu-item-eye" title="View details"><svg viewBox="0 0 24 24" width="18" height="18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="menu-item-eye-icon"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg></span></div></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="menu-modal" role="dialog" aria-modal="true" aria-labelledby="menu-modal-title" aria-hidden="true">
                <div class="menu-modal-backdrop" data-menu-close></div>
                <div class="menu-modal-panel" role="document">
                    <button class="menu-modal-close" type="button" aria-label="Close menu" data-menu-close>&times;</button>
                    <div class="menu-modal-image" aria-hidden="true"></div>
                    <div class="menu-modal-body">
                        <h3 id="menu-modal-title"></h3>
                        <div class="menu-modal-items"></div>
                    </div>
                </div>
            </div>

        </div>
            </section>
        </div>
    </div>
